language: c
sudo: required
compiler:
  - clang
  - gcc
env:
  - DEBUG_MODE=1
  - DEBUG_MODE=0
before_install:
  - sudo apt-get install xz-utils
  # Node.js
  - wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.xz
  - tar -C /usr/local --strip-components 1 -xJf node-v6.9.2-linux-x64.tar.xz
  - node -v
  - npm -v
before_script:
  - export DEBUG_SUFFIX=
  - if [ "$DEBUG_MODE" = "1" ]; then export DEBUG_SUFFIX=_debug; fi
script:
  - scons DEBUG=$DEBUG_MODE
  - python scripts/testsuite/test_programs.py DEBUG=$DEBUG_MODE